### PR TITLE
README.md: Windows tutorial

### PR DESCRIPTION
**Pull request by haslersn**

### CODE REVIEW

**Comment by spethso** [comment]
The command is still a bit annoying. It asks you for an input file.
`Running 'pdflatex  -recorder --jobname="jvk-blatt3-lsg"  \def\jvksolutions{}\input "jvk-blatt3.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7140 64-bit)
entering extended mode
! I can't find file `defjvksolutions{}input'.
<*> defjvksolutions{}input
                           jvk-blatt3.tex
Please type another input file name: jvk`

**Comment by haslersn** [comment]
> The command is still a bit annoying. It asks you for an input file.

This seems to be some quoting issue again. Which command did you use, and which command line interpreter/shell?

**Comment by spethso** [comment]
I used the normal windows cmd. The command is ```latexmk -pdf "-pdflatex=pdflatex %O \def\jvksolutions{}\input %S" -jobname=jvk-blatt1-lsg jvk-blatt1.tex```

**Comment by spethso** [comment]
Even after providing the input file manually, only the question version of the pdf is created, but stored as solution pdf

**Comment by haslersn** [comment]
> Even after providing the input file manually, only the question version of the pdf is created, but stored as solution pdf

Yes, that's expected. It's weird that it works on my windows machine, which according to the log calls `pdflatex` with exactly the same parameters and has exactly the same `pdflatex` version `3.14159265-2.6-1.40.20` installed.

**Pull request closed without merging**
